<?php # It is OK to edit this file but not the ones it generates. ?>
% The following text was generated by appA-ve_tuner.tex.php
% <?php echo shell_exec("date -R"); ?>

\begin{verbatim}
<?php
	# to run this file
	# php -f <this file>

	echo shell_exec("cat analyze/ve_tuner.R");
?>
\end{verbatim}
